import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { Miniflare } from 'miniflare';

let app, mf, db;
const tokens={rep:'rep-token',manager:'manager-token',foreign:'foreign-token'};
const schema=`
CREATE TABLE companies(id TEXT PRIMARY KEY,active INTEGER,subscription_status TEXT,trial_expires_at TEXT);
CREATE TABLE reps(id TEXT PRIMARY KEY,company_id TEXT,role TEXT,is_super_admin INTEGER,active INTEGER);
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
CREATE TABLE opportunities(id TEXT PRIMARY KEY,company_id TEXT,status TEXT,pipeline_stage TEXT,sales_process_stage_id TEXT,next_follow_up TEXT,source TEXT,assigned_to_rep_id TEXT,rep_id TEXT,email TEXT,phone TEXT,address TEXT,service_line TEXT,project TEXT,updated_at TEXT);
CREATE TABLE sales_process_versions(id TEXT PRIMARY KEY,company_id TEXT,process_id TEXT,lifecycle TEXT,published_at TEXT DEFAULT '');
CREATE TABLE sales_processes(id TEXT PRIMARY KEY,company_id TEXT,is_template INTEGER DEFAULT 0);
CREATE TABLE sales_process_stages(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stable_key TEXT,display_name TEXT,semantic_type TEXT,state TEXT,display_order INTEGER DEFAULT 0);
CREATE TABLE sales_stage_assignments(id TEXT PRIMARY KEY,company_id TEXT,opportunity_id TEXT,process_version_id TEXT,stage_id TEXT,classification TEXT,outcome_type TEXT,assigned_at TEXT,assigned_by TEXT);
CREATE TABLE sales_stage_transition_paths(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,from_stage_id TEXT,to_stage_id TEXT,requires_override INTEGER,override_policy TEXT,outcome_type TEXT,active INTEGER,display_label TEXT DEFAULT '',guidance TEXT DEFAULT '');
CREATE TABLE sales_stage_transitions(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,from_stage_id TEXT,to_stage_id TEXT,requires_override INTEGER,active INTEGER);
CREATE TABLE sales_stage_outcomes(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stage_id TEXT,semantic_type TEXT,active INTEGER);
CREATE TABLE sales_stage_requirements(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stage_id TEXT,requirement_type TEXT,stable_key TEXT,label TEXT,required_level TEXT,display_order INTEGER,config_json TEXT);
CREATE TABLE sales_stage_checklist_evidence(id TEXT PRIMARY KEY,company_id TEXT,opportunity_id TEXT,process_version_id TEXT,stage_id TEXT,requirement_id TEXT,completed INTEGER,evidence_json TEXT);
CREATE TABLE sales_stage_guides(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stage_id TEXT,guide_type TEXT,interaction_type TEXT,title TEXT,purpose TEXT,suggested_language TEXT,completion_guidance TEXT,display_order INTEGER,config_json TEXT);
CREATE TABLE sales_process_resources(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stage_id TEXT,resource_type TEXT,stable_key TEXT,name TEXT,content_json TEXT,active INTEGER);
CREATE TABLE sales_academy_skills(id TEXT PRIMARY KEY,company_id TEXT,stable_key TEXT,title TEXT,content_json TEXT,is_global INTEGER,active INTEGER);
CREATE TABLE sales_academy_associations(id TEXT PRIMARY KEY,company_id TEXT,process_version_id TEXT,stage_id TEXT,internal_status_id TEXT,skill_id TEXT,visibility TEXT,display_order INTEGER);
CREATE TABLE sales_stage_transition_events(id TEXT PRIMARY KEY,company_id TEXT,opportunity_id TEXT,process_version_id TEXT,from_stage_id TEXT,to_stage_id TEXT,outcome_type TEXT,actor_id TEXT,override_reason TEXT);
CREATE TABLE tasks(id TEXT PRIMARY KEY,company_id TEXT,title TEXT,due_date TEXT,linked_record_type TEXT,linked_record_id TEXT,status TEXT);
CREATE TABLE activity_log(id TEXT PRIMARY KEY,company_id TEXT,actor_id TEXT,actor_name TEXT,entity_type TEXT,entity_id TEXT,entity_label TEXT,action TEXT,before_json TEXT,after_json TEXT);
`;
async function request(token,body){const response=await app.request('http://test.local/api/opportunities/opp-a/stage-transition',{method:'POST',headers:{cookie:`avalon_session=${token}`,'content-type':'application/json'},body:JSON.stringify(body)},{DB:db});return {status:response.status,body:await response.json()};}
async function run(sql,...values){return db.prepare(sql).bind(...values).run();}

before(async()=>{
  app=(await import('../dist/_worker.js')).default;
  mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:`transitions-${Date.now()}`}});db=await mf.getD1Database('DB');await db.exec(schema);
  await db.batch([
    db.prepare("INSERT INTO companies VALUES ('company-a',1,'active',''),('company-b',1,'active','')"),
    db.prepare("INSERT INTO reps VALUES ('rep-a','company-a','representative',0,1),('manager-a','company-a','office_manager',0,1),('manager-b','company-b','office_manager',0,1)"),
    db.prepare("INSERT INTO settings VALUES ('session_rep-token','rep-a',''),('session_company_rep-token','company-a',''),('session_manager-token','manager-a',''),('session_company_manager-token','company-a',''),('session_foreign-token','manager-b',''),('session_company_foreign-token','company-b','')"),
    db.prepare("INSERT INTO sales_process_versions (id,company_id,process_id,lifecycle) VALUES ('v-a','company-a','p-a','published'),('v-b','company-b','p-b','published')"),
    db.prepare("INSERT INTO sales_processes VALUES ('p-a','company-a',0),('p-b','company-b',0)"),
    db.prepare("INSERT INTO sales_process_stages (id,company_id,process_version_id,stable_key,display_name,semantic_type,state,display_order) VALUES ('a-one','company-a','v-a','one','One','intake','active',1),('a-two','company-a','v-a','two','Two','consultation','active',2),('a-three','company-a','v-a','three','Three','decision','active',3),('b-one','company-b','v-b','one','One','intake','active',1)"),
    db.prepare("INSERT INTO opportunities VALUES ('opp-a','company-a','','','a-one','','','','rep-a','','','','','','seed'),('opp-b','company-b','','','b-one','','','','manager-b','','','','','','seed')"),
    db.prepare("INSERT INTO sales_stage_assignments VALUES ('asg-a','company-a','opp-a','v-a','a-one','mapped','','','rep-a'),('asg-b','company-b','opp-b','v-b','b-one','mapped','','','manager-b')"),
    db.prepare("INSERT INTO sales_stage_transition_paths (id,company_id,process_version_id,from_stage_id,to_stage_id,requires_override,override_policy,outcome_type,active) VALUES ('path-normal','company-a','v-a','a-one','a-two',0,'stage_policy','',1),('path-manager','company-a','v-a','a-one','a-three',1,'manager_required','',1)"),
    db.prepare("INSERT INTO sales_stage_requirements VALUES ('req-bool','company-a','v-a','a-one','checklist','confirmed','Confirmed','required',1,'{\"phase\":\"exit\"}'),('req-action','company-a','v-a','a-one','field','next_action','Next action','required',2,'{\"phase\":\"exit\"}'),('req-date','company-a','v-a','a-one','field','next_action_date','Next action date','required',3,'{\"phase\":\"exit\"}')"),
    db.prepare("INSERT INTO sales_stage_checklist_evidence VALUES ('ev','company-a','opp-a','v-a','a-one','req-bool',1,'{\"value\":false}')"),
    db.prepare("INSERT INTO tasks VALUES ('task-a','company-a','Call customer','2026-08-01','opportunity','opp-a','open')")
    ,db.prepare("INSERT INTO sales_stage_guides VALUES ('guide-a','company-a','v-a','a-one','call_guide','qualification_call','Qualification','Confirm fit','Ask about priorities','Record next step',1,'{\"questions\":[\"What matters most?\"]}')")
    ,db.prepare("INSERT INTO sales_process_resources VALUES ('resource-a','company-a','v-a','a-one','email_template','recap','Recap','{}',1)")
    ,db.prepare("INSERT INTO sales_academy_skills VALUES ('skill-global','__global__','qualification','Qualification skill','{}',1,1),('skill-foreign','company-b','foreign','Foreign skill','{}',0,1)")
    ,db.prepare("INSERT INTO sales_academy_associations VALUES ('association-a','company-a','v-a','a-one','','skill-global','representative',1),('association-b','company-b','v-b','b-one','','skill-foreign','representative',1)")
  ]);
  await db.exec("ALTER TABLE opportunities ADD COLUMN job_value REAL DEFAULT 0");
  await db.exec("ALTER TABLE opportunities ADD COLUMN client TEXT DEFAULT ''");
});
after(async()=>mf.dispose());

test('boolean false remains incomplete and response identifies missing evidence',async()=>{const result=await request(tokens.rep,{expected_stage_id:'a-one',stage_id:'a-two'});assert.equal(result.status,409);assert.equal(result.body.data.code,'sales_transition_evidence_incomplete');assert.equal(result.body.data.override_required,true);assert.equal(result.body.data.manager_required,true);assert.deepEqual(result.body.data.missing_requirements.map(r=>r.stable_key),['confirmed']);});
test('task title and due date satisfy blank next-action opportunity fields',async()=>{await run("UPDATE sales_stage_checklist_evidence SET evidence_json='{\"value\":true}' WHERE id='ev'");const result=await request(tokens.rep,{expected_stage_id:'a-one',stage_id:'a-two'});assert.equal(result.status,200);assert.equal(result.body.data.stage.id,'a-two');await run("UPDATE sales_stage_assignments SET stage_id='a-one' WHERE id='asg-a'");await run("UPDATE opportunities SET sales_process_stage_id='a-one' WHERE id='opp-a'");});
test('manager-required path rejects representatives with structured override response',async()=>{const result=await request(tokens.rep,{expected_stage_id:'a-one',stage_id:'a-three',override_reason:'rep cannot self-approve'});assert.equal(result.status,403);assert.equal(result.body.data.code,'sales_transition_override_required');assert.equal(result.body.data.manager_required,true);});
test('manager override requires a reason and succeeds without changing another tenant',async()=>{let result=await request(tokens.manager,{expected_stage_id:'a-one',stage_id:'a-three'});assert.equal(result.status,409);assert.equal(result.body.data.override_required,true);result=await request(tokens.manager,{expected_stage_id:'a-one',stage_id:'a-three',override_reason:'Reviewed with representative'});assert.equal(result.status,200);const foreign=await db.prepare("SELECT sales_process_stage_id FROM opportunities WHERE id='opp-b' AND company_id='company-b'").first();assert.equal(foreign.sales_process_stage_id,'b-one');});
test('another company cannot transition the tenant opportunity',async()=>{const result=await request(tokens.foreign,{expected_stage_id:'a-three',stage_id:'a-two',override_reason:'foreign'});assert.equal(result.status,409);});
test('Stage Guide Call Companion and Academy context is version-owned and tenant isolated',async()=>{await run("UPDATE sales_stage_assignments SET stage_id='a-one' WHERE id='asg-a'");await run("UPDATE opportunities SET sales_process_stage_id='a-one' WHERE id='opp-a'");const response=await app.request('http://test.local/api/opportunities/opp-a/sales-context',{headers:{cookie:'avalon_session=rep-token'}},{DB:db});assert.equal(response.status,200);const payload=await response.json();assert.equal(payload.data.normalized,true);assert.equal(payload.data.stage.id,'a-one');assert.equal(payload.data.guides[0].interaction_type,'qualification_call');assert.equal(payload.data.resources[0].stable_key,'recap');assert.deepEqual(payload.data.academy_skills.map(skill=>skill.id),['skill-global']);assert.ok(payload.data.transitions.every(transition=>transition.to_stage_id.startsWith('a-')));});
test('company Academy playbook follows the published process and excludes foreign training',async()=>{const response=await app.request('http://test.local/api/sales-process/playbook',{headers:{cookie:'avalon_session=rep-token'}},{DB:db});assert.equal(response.status,200);const payload=(await response.json()).data;assert.equal(payload.normalized,true);assert.deepEqual(payload.stages.map(stage=>stage.id),['a-one','a-two','a-three']);assert.deepEqual(payload.stages[0].training.map(skill=>skill.skill_id),['skill-global']);assert.ok(payload.stages.every(stage=>stage.training.every(skill=>skill.skill_id!=='skill-foreign')));});
test('AI coaching uses normalized outcomes and excludes unresolved records from stagnation',async()=>{await run("UPDATE opportunities SET client='Active',updated_at='2020-01-01',job_value=100 WHERE id='opp-a'");await run("INSERT INTO opportunities (id,company_id,status,pipeline_stage,sales_process_stage_id,next_follow_up,source,assigned_to_rep_id,rep_id,email,phone,address,service_line,project,updated_at,job_value,client) VALUES ('opp-unresolved','company-a','Renamed unknown','','','','','','rep-a','','','','','','2020-01-01',200,'Unresolved'),('opp-won','company-a','Not a won label','','a-three','','','','rep-a','','','','','','2020-01-01',300,'Won')");await run("INSERT INTO sales_stage_assignments VALUES ('asg-won','company-a','opp-won','v-a','a-three','mapped','won','','manager-a')");const response=await app.request('http://test.local/api/ai/assistant/context',{headers:{cookie:'avalon_session=manager-token'}},{DB:db});assert.equal(response.status,200);const payload=(await response.json()).data;assert.equal(payload.pipeline.open,2);assert.equal(payload.pipeline.value,300);assert.ok(payload.recommendations.some(item=>item.id==='stale_opp-a'));assert.ok(payload.recommendations.every(item=>!String(item.id).includes('opp-unresolved')||item.type!=='stale_lead'));assert.ok(payload.recommendations.every(item=>!String(item.id).includes('opp-won')));});
